name: Deploy portfolio-tutorial to linode VPS with Docker

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3  # ✅ Upgraded to v3

      # Step 2: Set up Docker Buildx (Fixed deprecated warnings)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # ✅ Upgraded to v2

      # Step 3: Set up SSH agent to authenticate with the linode VPS using the private SSH key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0  # ✅ Upgraded to latest version
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: SSH into linode VPS and deploy Docker container with retry mechanism
      - name: SSH into linode VPS and deploy Docker container
        run: |
          RETRIES=5
          DELAY=1

          for ((i=1; i<=RETRIES; i++)); do
            echo "Attempt $i to SSH into the linode VPS..."
            
            ssh -o StrictHostKeyChecking=no root@66.228.58.89 "
              # Ensure the projects directory exists
              mkdir -p /var/www/html/projects &&

              # Clone the repository if it doesn't exist
              if [ ! -d /var/www/html/projects/portfolio-tutorial ]; then
                git clone git@github.com:ongudidan/portfolio-tutorial.git /var/www/html/projects/portfolio-tutorial
              fi &&

              # Navigate to the project directory
              cd /var/www/html/projects/portfolio-tutorial &&

              # Reset and pull latest code
              git reset --hard origin/main &&
              git pull origin main &&

              # Restart the Docker containers
              docker compose down &&
              docker compose up --build -d
            " && break

            echo "SSH attempt $i failed. Retrying in $DELAY seconds..."
            sleep $DELAY
          done
